// File generated by FlutterFire CLI.
// Configuration for LY-Elite Tourism Group (مجموعة النخبة للخدمات السياحية)
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyEliteTourismGroupWeb',
    appId: '1:402147618508:web:7a8b9c0d1e2f',
    messagingSenderId: '402147618508',
    projectId: 'ly-elite-tourism',
    authDomain: 'ly-elite-tourism.firebaseapp.com',
    storageBucket: 'ly-elite-tourism.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyEliteTourismGroupAndroid',
    appId: '1:402147618508:android:8b9c0d1e2f3a',
    messagingSenderId: '402147618508',
    projectId: 'ly-elite-tourism',
    storageBucket: 'ly-elite-tourism.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyEliteTourismGroupIos',
    appId: '1:402147618508:ios:9c0d1e2f3a4b',
    messagingSenderId: '402147618508',
    projectId: 'ly-elite-tourism',
    storageBucket: 'ly-elite-tourism.appspot.com',
    iosBundleId: 'com.lyelite.tourism.customer',
  );
}
