import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/constants/company_contacts.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/utils/whatsapp_helper.dart';
import '../../../core/providers/repository_providers.dart';
import 'package:core_domain/entities/travel_package_entity.dart';
import 'package:core_domain/entities/booking_entity.dart';

class BookingModal extends ConsumerStatefulWidget {
  final TravelPackageEntity package;

  const BookingModal({super.key, required this.package});

  @override
  ConsumerState<BookingModal> createState() => _BookingModalState();
}

class _BookingModalState extends ConsumerState<BookingModal> {
  final _formKey = GlobalKey<FormState>();

  late DateTime _startDate;
  late DateTime _returnDate;
  int _adultsCount = 2;
  int _childrenCount = 0;

  final TextEditingController _nameController =
      TextEditingController(text: 'عبد الباري معتوق');
  final TextEditingController _phoneController =
      TextEditingController(text: '+218915919921');
  final TextEditingController _notesController = TextEditingController();

  bool _isSubmitting = false;

  @override
  void initState() {
    super.initState();
    _startDate = DateTime.now().add(const Duration(days: 14));
    _returnDate = _startDate.add(Duration(days: widget.package.durationDays));
  }

  @override
  void dispose() {
    _nameController.dispose();
    _phoneController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _submitBooking() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isSubmitting = true);

    try {
      final bookingRepo = ref.read(bookingRepositoryProvider);

      final totalEstimated = widget.package.price * _adultsCount +
          (widget.package.price * 0.6 * _childrenCount);

      final booking = BookingEntity(
        id: '',
        referenceNumber: '', // Auto-generated by repository
        packageId: widget.package.id,
        packageTitle: widget.package.title,
        packageDestination: widget.package.destination,
        userId: 'current_user_uid',
        customerName: _nameController.text.trim(),
        customerPhone: _phoneController.text.trim(),
        startDate: _startDate,
        returnDate: _returnDate,
        durationDays: widget.package.durationDays,
        adultsCount: _adultsCount,
        childrenCount: _childrenCount,
        estimatedTotal: totalEstimated,
        notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
        targetWhatsAppNumber: CompanyContacts.primaryWhatsApp,
        createdAt: DateTime.now(),
      );

      // 1. Save in Firestore as pending
      final createdBooking = await bookingRepo.createBooking(booking);

      // 2. Prepare pre-filled WhatsApp message
      final message = '''
السلام عليكم، أود حجز الباقة السياحية التالية:
🌟 اسم الباقة: ${widget.package.title}
📍 الوجهة: ${widget.package.destination}
🔖 الرقم المرجعي: ${createdBooking.referenceNumber}
📅 تاريخ المغادرة: ${_startDate.year}-${_startDate.month.toString().padLeft(2, '0')}-${_startDate.day.toString().padLeft(2, '0')}
👥 المسافرون: $_adultsCount بالغين، $_childrenCount أطفال
👤 اسم العميل: ${_nameController.text.trim()}
📱 رقم الهاتف: ${_phoneController.text.trim()}
${_notesController.text.trim().isNotEmpty ? '📝 ملاحظات: ${_notesController.text.trim()}' : ''}

يرجى تزويدي بتفاصيل تأكيد الحجز وإتمام الدفع يدوياً مع فريق المبيعات.
''';

      // 3. Launch WhatsApp directly to primary company number
      await WhatsAppHelper.launchWhatsApp(
        phoneNumber: CompanyContacts.primaryWhatsApp,
        message: message,
      );

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: const Color(0xFF059669),
            content: Text(
              'تم حفظ الحجز بنجاح بالرقم: ${createdBooking.referenceNumber} وجارٍ فتح واتساب للمتابعة...',
              textDirection: TextDirection.rtl,
            ),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            backgroundColor: const Color(0xFFDC2626),
            content: Text('حدث خطأ: $e', textDirection: TextDirection.rtl),
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isSubmitting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom,
      ),
      decoration: const BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
      ),
      child: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(20),
          child: Form(
            key: _formKey,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              mainAxisSize: MainAxisSize.min,
              children: [
                // Top handle
                Center(
                  child: Container(
                    width: 40,
                    height: 4,
                    decoration: BoxDecoration(
                      color: AppColors.lightDividers,
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                ),
                const SizedBox(height: 16),

                // Modal Header
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'طلب حجز الباقة',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                            color: AppColors.primaryNavy,
                          ),
                        ),
                        Text(
                          widget.package.title,
                          style: const TextStyle(
                            fontSize: 12,
                            color: AppColors.accentGold,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                      ],
                    ),
                    IconButton(
                      icon: const Icon(Icons.close),
                      onPressed: () => Navigator.pop(context),
                    ),
                  ],
                ),

                const SizedBox(height: 12),
                Container(
                  padding: const EdgeInsets.all(10),
                  decoration: BoxDecoration(
                    color: AppColors.goldSoftBg,
                    borderRadius: BorderRadius.circular(12),
                    border: Border.all(color: AppColors.accentGold.withOpacity(0.3)),
                  ),
                  child: const Row(
                    children: [
                      Icon(Icons.info_outline, color: AppColors.accentGold, size: 18),
                      SizedBox(width: 8),
                      Expanded(
                        child: Text(
                          'لا يوجد دفع إلكتروني. سيتم حفظ طلبك وتحويلك فورياً لواتساب لإتمام التفاصيل والدفع يدوياً مع فريق المبيعات.',
                          style: TextStyle(fontSize: 11, color: AppColors.primaryNavy),
                        ),
                      ),
                    ],
                  ),
                ),

                const SizedBox(height: 20),

                // Date Picker Tile
                const Text('تاريخ بداية الرحلة', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 13)),
                const SizedBox(height: 6),
                InkWell(
                  onTap: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: _startDate,
                      firstDate: DateTime.now(),
                      lastDate: DateTime.now().add(const Duration(days: 365)),
                    );
                    if (picked != null) {
                      setState(() {
                        _startDate = picked;
                        _returnDate = picked.add(Duration(days: widget.package.durationDays));
                      });
                    }
                  },
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
                    decoration: BoxDecoration(
                      border: Border.all(color: AppColors.lightDividers),
                      borderRadius: BorderRadius.circular(12),
                      color: AppColors.lightBackground,
                    ),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Text(
                          '${_startDate.year}/${_startDate.month}/${_startDate.day} (العودة: ${_returnDate.year}/${_returnDate.month}/${_returnDate.day})',
                          style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 13),
                        ),
                        const Icon(Icons.calendar_month, color: AppColors.accentGold, size: 20),
                      ],
                    ),
                  ),
                ),

                const SizedBox(height: 16),

                // Travelers Count (Adults & Children)
                Row(
                  children: [
                    Expanded(
                      child: _buildCounterTile(
                        title: 'البالغين (+12)',
                        value: _adultsCount,
                        onAdd: () => setState(() => _adultsCount++),
                        onRemove: () {
                          if (_adultsCount > 1) setState(() => _adultsCount--);
                        },
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: _buildCounterTile(
                        title: 'الأطفال (2-11)',
                        value: _childrenCount,
                        onAdd: () => setState(() => _childrenCount++),
                        onRemove: () {
                          if (_childrenCount > 0) setState(() => _childrenCount--);
                        },
                      ),
                    ),
                  ],
                ),

                const SizedBox(height: 16),

                // Name and Phone fields
                TextFormField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    labelText: 'الاسم الكامل *',
                    border: OutlineInputBorder(),
                  ),
                  validator: (v) => v == null || v.trim().isEmpty ? 'يرجى إدخال الاسم' : null,
                ),
                const SizedBox(height: 12),
                TextFormField(
                  controller: _phoneController,
                  keyboardType: TextInputType.phone,
                  decoration: const InputDecoration(
                    labelText: 'رقم الهاتف (واتساب) *',
                    border: OutlineInputBorder(),
                  ),
                  validator: (v) => v == null || v.trim().isEmpty ? 'يرجى إدخال رقم الهاتف' : null,
                ),

                const SizedBox(height: 12),

                TextFormField(
                  controller: _notesController,
                  maxLines: 2,
                  decoration: const InputDecoration(
                    labelText: 'ملاحظات خاصة (اختياري)',
                    hintText: 'طلبات غذائية، إطلالة معينة، سرير أطفال...',
                    border: OutlineInputBorder(),
                  ),
                ),

                const SizedBox(height: 20),

                // Submit Button
                SizedBox(
                  width: double.infinity,
                  child: ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: AppColors.accentGold,
                      foregroundColor: AppColors.primaryNavyDark,
                      padding: const EdgeInsets.symmetric(vertical: 14),
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(14),
                      ),
                    ),
                    onPressed: _isSubmitting ? null : _submitBooking,
                    child: _isSubmitting
                        ? const CircularProgressIndicator(color: AppColors.primaryNavyDark)
                        : const Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              Icon(Icons.send_rounded, size: 18),
                              SizedBox(width: 8),
                              Text(
                                'إرسال الطلب ومتابعة الحجز عبر واتساب',
                                style: TextStyle(
                                  fontSize: 14,
                                  fontWeight: FontWeight.bold,
                                ),
                              ),
                            ],
                          ),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildCounterTile({
    required String title,
    required int value,
    required VoidCallback onAdd,
    required VoidCallback onRemove,
  }) {
    return Container(
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        border: Border.all(color: AppColors.lightDividers),
        borderRadius: BorderRadius.circular(12),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(title, style: const TextStyle(fontSize: 12, color: AppColors.lightTextSecondary)),
          const SizedBox(height: 6),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              IconButton(
                icon: const Icon(Icons.remove_circle_outline, size: 22, color: AppColors.primaryNavy),
                onPressed: onRemove,
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(),
              ),
              Text('$value', style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
              IconButton(
                icon: const Icon(Icons.add_circle_outline, size: 22, color: AppColors.primaryNavy),
                onPressed: onAdd,
                padding: EdgeInsets.zero,
                constraints: const BoxConstraints(),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
